# Generated by Django 5.2.3 on 2025-08-27 08:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense_track', '0002_alter_expense_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(default=datetime.date(2025, 8, 27)),
        ),
    ]
